api: v0.0.1
actions:
  - name: build_and_test_the_code
    script: |-      
      cp -r /opt/dbunit-runner .

      cp assignment/*.sql dbunit-runner/src/test/resources/assignment/
      cp *.sql dbunit-runner/src/test/resources/
      cp *.xml dbunit-runner/src/test/resources/

      java_file="public class DbUnitTest extends BaseDbUnitTest {
      "
      
      for file in *.sql; do
          if [ "$file" != "schema.sql" ]; then
              file=$(basename $file .sql)
              java_file+="public void test_${file}() throws Exception {
              sqlFiles(\"${file}\", \"${file}\");
          }
          "
          fi
      done
      java_file+="}"
      
      echo $java_file > dbunit-runner/src/test/java/DbUnitTest.java

      cd dbunit-runner && mvn clean test
    runAlways: false
    results:
      - name: junit
        path: '**/target/surefire-reports/*.xml'
        type: junit